# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run tests
      run: xcodebuild test -scheme WhatsNew -destination 'platform=iOS Simulator,name=iPhone 17 Pro,OS=26.0' | xcpretty
